version: '3.7'
services: 

  rabbitmq:
    image: rabbitmq:3.8.12-management
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"  
    networks:
      - currency-network
      
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    depends_on:
      - rabbitmq
    restart: always
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672  
      
networks:
  currency-network: